project: 
  type: website
  output-dir: "." 

website:
  title: "Aaron Zalen's website"
navbar:
  left:
  - text: "Home" 
href: index.qmd
- text: "Project" 
href: danl_210_ZALEN_AARON_stock_ESG.qmd
- text: "Blog"
href: blog-listing.qmd
            
  page-footer: 
    center: "Powered with GitHub, Quarto, and Jupyter Notebook<br>© YOUR NAME, 2025"

format:
  html:
    theme: 
      light: flatly # flatly sandstone yeti united litera journal
      dark: darkly #  darkly cyborg slate solra superhero
    mainfont: system-ui; 
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
    toc: false
    include-after-body: target_blank.html

